### ISSUE TITLE
Suggestions + improvements

### ISSUE THREAD

**Issue by pavolgaj** [pavolgaj/OCFit#13]
I start to make a big code change. I mainly want to use the `emcee` package for Monte Carlo fitting (instead of quite old `pymc v2`). If someone has some suggestions on what to change in the OCFit package and/or GUI, please, write here. I also have some;)
Hopefully, the completely new version will be published this year...

### Planned changes
- [x] MC fitting using `emcee` - changes in fitting function, `InfoMCMC` class and GUI (`Fit.Params` window - https://github.com/pavolgaj/OCFit/commit/9f53a82ee69983b59919aca1b2ac031a7263b91c) - done in https://github.com/pavolgaj/OCFit/commit/b5e4f7ca027175d8dd209f023af9a9c5b6aff9ad
- [x] calculation of absolute params. in GUI (https://github.com/pavolgaj/OCFit/issues/4) - maybe add a new window to set required params (https://github.com/pavolgaj/OCFit/commit/82155fcb7d020fb6e681d02e11dd8c53512c54bc)
- [x] remember values set in `FitParams` in GUI and set them after reopening this window (https://github.com/pavolgaj/OCFit/issues/4) - https://github.com/pavolgaj/OCFit/commit/01363802f6cf2d9e3f7f5bba636598d38e2c524f (for old MCMC)
- [x] adding some new models: Quad+Apsidal (added in https://github.com/pavolgaj/OCFit/commit/dc833b3cef9befbaad01238daddd090e6d8f7c9f), ~~maybe ETV model of Borkovits (https://github.com/pavolgaj/OCFit/issues/5)~~
- [x] epoch calculation for elliptic orbits (https://github.com/pavolgaj/OCFit/issues/1) - in `OCFit` (https://github.com/pavolgaj/OCFit/commit/2b6d7438bd1a830e774e53917151c883db3e96ab) and GUI (https://github.com/pavolgaj/OCFit/commit/81823d1a8b7130dd25653bf7fdd87e0c23e4340e)
- [x] store data in JSON except for the pickle file - done in https://github.com/pavolgaj/OCFit/commit/aa4e97af228b675c6c2737ced5107d899d65782f
- [x] change fitting from GA to scipy DE (https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.differential_evolution.html) - add DE as new function (https://github.com/pavolgaj/OCFit/commit/6478182de3f06b2e9d98552a1c75bfca7e34a042 and https://github.com/pavolgaj/OCFit/commit/60730b25682cb5d0fa5cb8fdb4c4d1faf61d0258 - GUI)
- [x] calculation of additional params (e.g. dP, dM) from quadratic model - https://github.com/pavolgaj/OCFit/commit/dc833b3cef9befbaad01238daddd090e6d8f7c9f
- [x] add buttons for running InfoMCMC (or maybe also InfoGA) to GUI - https://github.com/pavolgaj/OCFit/commit/fdf15575134c85c265110039149ee2328547815a
- [x] change FitLinear/FitQuad in GUI - fitting methods (standard, robust, MC) - new Window FitParams (https://github.com/pavolgaj/OCFit/commit/537bb2ec2df6345f563ac9e4a05dd6f5d72f0f09)
- [x] GUI: update ephemeris after button press (https://github.com/pavolgaj/OCFit/commit/4229b9561c1a5c45f27793d52eb9de2e630a5ce0)
- [ ] update docs on GitHub/Wiki page
- [x] add models: LiTE3+Apsidal and LiTE3Quad+Apsidal (or LiTE3+ApsidalQuad) - https://github.com/pavolgaj/OCFit/commit/5f51946809c3bb59690440251cd69f53fb234153

**Comment by kolarjakubmuni** [comment]
Hi. I would suggest the possibility of fitting more than one phenomenon in the O-C diagram, e.g. parabolic change with apsidal motion, etc. For my field of study (quadruple eclipsing systems) we have usually two O-C diagrams, for pair A and B. We could fit them separately for knowing what is happening with the pair. However, these two pairs are gravitationally bound and influence each other. So their O-C diagrams can show us their mutual motion. Maybe it should be very useful to fit both O-C diagrams together. Of course both pairs have different ephemeris values and it would be quite large change in the software.

![image](https://user-images.githubusercontent.com/105272977/167578063-64b1434b-aa9e-4c5e-bc5f-0ce6cf68958c.png)
From the paper Zasche et al. 2019, there is an example of the O-C diagrams for both pairs.

**Comment by pavolgaj** [comment]
A combination of parabolic trend and apsidal motion is easy to implement. 

The quadrupole systems are fascinating but fitting the O-Cs from both pairs together would be really complicated and I don't know if it would have some benefits. It would be necessary to load and store O-Cs separately which requires changing a big part of the code (initialization, fitting, plotting etc.). And only parameter that should be the same for O-Cs of both pairs is their mutual orbital period (label as P3 in OCFit). I don't plan to implement this possibility, now - maybe if I'll study such systems, my opinion changes;)

**Comment by pavolgaj** [comment]
I just changed the FitMCMC function to use the `emcee` package (commit https://github.com/pavolgaj/OCFit/commit/b5e4f7ca027175d8dd209f023af9a9c5b6aff9ad in a dev branch). I'm open to any of your comments or possible issues with it. 
The original function (used pymc) was renamed to `FitMCMC_old` and the old InfoMC class moved to file `info_mc_old.py` - emcee and pymc generate a bit different output files. 

I compared pymc and emcee fitting and they give very similar results. Maybe, the emcee gives more realistic posterior distributions. And from my point of view, fitting using an emcee is faster.

**Comment by kolarjakubmuni** [comment]
Maybe the fitting primary and secondary minima, which are vertically shifted simultaneously. Something like this. 
![image](https://user-images.githubusercontent.com/105272977/170071260-c8bae148-cce1-4f5e-96d2-4eb2f06454a2.png)
(From my preliminary results of one system.)

**Comment by pavolgaj** [comment]
@kolarjakubmuni Interesting... The difference in O-Cs for primary and secondary for nearly 6 hours is something strange. Could you write some specifications for this system? Isn't it eccentric?

**Comment by pavolgaj** [comment]
Change default file format from pickle to JSON (https://github.com/pavolgaj/OCFit/commit/aa4e97af228b675c6c2737ced5107d899d65782f). The format can be changed manually with parameter `format` in the `Save` function - it has 2 possible values `'json'` or `'pickle'`. Detection of the file format before loading it is done automatically. So, loading files saved in the older version of OCFit (pickle format) is possible.

**Comment by pavolgaj** [comment]
Added new function `FitDE` for fitting using Differential Evolution from scipy (https://github.com/pavolgaj/OCFit/commit/6478182de3f06b2e9d98552a1c75bfca7e34a042). It's an alternative method to Genetic Algorithms in the `FitGA` function. DE should be a bit faster compared to GA because of internal converge control - not all iterations need to be run.

**Comment by pavolgaj** [comment]
@kolarjakubmuni:
 > Hi. I would suggest the possibility of fitting more than one phenomenon in the O-C diagram, e.g. parabolic change with apsidal motion, etc. 

I just implement a new model called ApsidalQuad. I don't have any good data to test it but I don't expect any problems.

**Comment by kolarjakubmuni** [comment]
> @kolarjakubmuni Interesting... The difference in O-Cs for primary and secondary for nearly 6 hours is something strange. Could you write some specifications for this system? Isn't it eccentric?

Yes, the difference is quite large. We don't know much about the system, it should be quadruple doubly eclipsing. So there is probably a combination with more effects and the system is probably eccentric. However, the secondary minima are very shallow and we need to confirm these differences (this is from the TESS data).

**Comment by pavolgaj** [comment]
Commit https://github.com/pavolgaj/OCFit/commit/2b6d7438bd1a830e774e53917151c883db3e96ab solves the problem with eccentric orbits (https://github.com/pavolgaj/OCFit/issues/1). New function `DeltaEpoch` calculate phase (difference in epoch) for secondary minima from eccentricity and argument of pericenter. All classes have a new input parameter `dE` which is used to calculate epochs and types of minima.

**Comment by pavolgaj** [comment]
@kjkoeller I start to modify GUI. I just added some new buttons - so I had to make the main window a bit larger. Could you check if it looks good also on bigger screens (with set `fixed=False` - line 2908). If not, please, change `screenheight` on line 2916.

**Comment by pavolgaj** [comment]
Added function to calculate or estimate phase (difference in epoch) of secondary minima in GUI (https://github.com/pavolgaj/OCFit/commit/81823d1a8b7130dd25653bf7fdd87e0c23e4340e). Estimation is done from the difference between O-Cs of primary and secondary minima.

**Comment by pavolgaj** [comment]
Added new window InfoMCMC in GUI. It can load saved sampling of MCMC or GA/DE fitting from a file and generate some figures useful for analysing sampling. Files generated by `pymc` are not supported! Only files from `emcee` could be used.

**Comment by pavolgaj** [comment]
Implemented new fitting methods (Robust Regression and MCMC) for FitLinear and FitQuad in GUI (https://github.com/pavolgaj/OCFit/commit/537bb2ec2df6345f563ac9e4a05dd6f5d72f0f09). Added new window FitParams for setting necessary parameters.

**Comment by pavolgaj** [comment]
Merged to master branch. Uploaded to PyPI. Created a new release.

**Comment by pavolgaj** [comment]
Added models LiTE3Apsidal and LiTE3ApsidalQuad (https://github.com/pavolgaj/OCFit/commit/5f51946809c3bb59690440251cd69f53fb234153).
